### ISSUE TITLE
Export 중 발생한 오류 조치한 것 공유드립니다.

### ISSUE THREAD

**Issue by KingPiggy** [uyu423/resume-nextjs#18]
안녕하세요~!
npm run export 명령 실행중 오류 조치한 내용이 있어 내용 공유 드립니다.

	eslint 'component/**/*' 'pages/**/*' 'payload/**/*' '*.ts' --fix

	Oops! Something went wrong! :(

	ESLint: 6.8.0.

	No files matching the pattern "'component/**/*'" were found.
	Please check for typing mistakes in the pattern.

package.json 파일의 lint 부분 코드를 수정하여 조치했습니다.

	"lint": "eslint \"component/**/*\" \"pages/**/*\" \"payload/**/*\" \"*.ts\" --fix",

**Comment by HDK7** [comment]
같은 오류 발생했는데 감사합니다 ~!~

**Comment by uyu423** [comment]
close https://github.com/uyu423/resume-nextjs/commit/e86177ac084a78345c3c2e15631beee38a4c667f
