### ISSUE TITLE
production 빌드에서 이미지가 깨지는 경우

### ISSUE THREAD

**Issue by hongdor** [uyu423/resume-nextjs#24]
package.json 파일에서

  "homepage": "https://uyu423.github.io/resume-nextjs"

항목의 subpath "/resume-nextjs"가 asset의 path prefix로 들어가기 때문에 

  "homepage": "https://uyu423.github.io" 

로 바꾸어서 테스트 하시거나 자기 홈페이지로 바꾸시고 진행하시면 될 것 같습니다.

**Comment by uyu423** [comment]
이슈 공유 감사합니다. 요 내용은 저도 테스트해보고 필요하면 README.md 에 포함시키겠습니다. 👍👍
